# Generated by Django 3.2.2 on 2021-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=12)),
                ('mgmt_ip', models.CharField(max_length=136)),
                ('vtep_ip', models.CharField(max_length=136)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('deleted_at', models.DateTimeField(verbose_name='删除时间')),
            ],
        ),
    ]
