# Generated by Django 3.2.2 on 2021-06-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdnet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchs',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='删除时间'),
        ),
    ]
